package com.gildedrose;

enum QualityGroup {
    REGULAR_AGED,
    DOUBLE_AGED_EXPIRED,
    EVERLASTING,
    MATURED,
    DOUBLE_MATURED_REMAINING_DAYS_10,
    TRIPLE_MATURED_REMAINING_DAYS_5,
    DOUBLE_AGED
}
